package nezet;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class AutoMegjelenito extends javax.swing.JFrame {

    public AutoMegjelenito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbRendszam = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chbDohanyzas = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtFizetesiMod = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuProgram = new javax.swing.JMenu();
        mnuPrgMentes = new javax.swing.JMenuItem();
        mnuPrgBetolt = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuPrgKilep = new javax.swing.JMenuItem();
        mnuLekerdezes = new javax.swing.JMenu();
        mnuLkOszz = new javax.swing.JMenuItem();
        mnuLkDohanyzas = new javax.swing.JMenuItem();
        mnuLkLeghosszF = new javax.swing.JMenuItem();
        mnuLkKikDolgoztak = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Válasszon rendszámot:");

        jLabel3.setText("Lehet doháyozni?:");

        chbDohanyzas.setText("Igen / Nem");
        chbDohanyzas.setEnabled(false);

        jLabel5.setText("Támogatott fizetési mód:");

        mnuProgram.setText("Program");

        mnuPrgMentes.setText("Mentés");
        mnuProgram.add(mnuPrgMentes);

        mnuPrgBetolt.setText("Betöltés");
        mnuPrgBetolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgBetoltActionPerformed(evt);
            }
        });
        mnuProgram.add(mnuPrgBetolt);
        mnuProgram.add(jSeparator1);

        mnuPrgKilep.setText("Kilépés");
        mnuPrgKilep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrgKilepActionPerformed(evt);
            }
        });
        mnuProgram.add(mnuPrgKilep);

        jMenuBar1.add(mnuProgram);

        mnuLekerdezes.setText("Lekérdezések");

        mnuLkOszz.setText("Össz bevétel");
        mnuLekerdezes.add(mnuLkOszz);

        mnuLkDohanyzas.setText("Minden autóba lehet dohányozni");
        mnuLekerdezes.add(mnuLkDohanyzas);

        mnuLkLeghosszF.setText("Leghosszabb fuvar");
        mnuLkLeghosszF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLkLeghosszFActionPerformed(evt);
            }
        });
        mnuLekerdezes.add(mnuLkLeghosszF);

        mnuLkKikDolgoztak.setText("Kik dolgoztak 202.12.31-én?");
        mnuLekerdezes.add(mnuLkKikDolgoztak);

        jMenuBar1.add(mnuLekerdezes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chbDohanyzas)
                            .addComponent(txtFizetesiMod)
                            .addComponent(cmbRendszam, 0, 132, Short.MAX_VALUE)))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbRendszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFizetesiMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chbDohanyzas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPrgBetoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgBetoltActionPerformed
        
    }//GEN-LAST:event_mnuPrgBetoltActionPerformed

    private void mnuLkLeghosszFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLkLeghosszFActionPerformed
        
    }//GEN-LAST:event_mnuLkLeghosszFActionPerformed

    private void mnuPrgKilepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrgKilepActionPerformed
        kilepes();
    }//GEN-LAST:event_mnuPrgKilepActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        kilepes();
    }//GEN-LAST:event_formWindowClosing

    private void kilepes() throws HeadlessException {
        String msg = "Biztos kilépsz?";
        String cim = "Kilépés";
        int msgTip = JOptionPane.QUESTION_MESSAGE;
        int optTip = JOptionPane.YES_NO_OPTION;
        int gomb = JOptionPane.showConfirmDialog(rootPane, msg, cim, optTip);
        if (gomb == JOptionPane.YES_OPTION) {
            int hibaKod = 0;
            System.exit(hibaKod);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoMegjelenito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoMegjelenito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoMegjelenito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoMegjelenito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoMegjelenito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbDohanyzas;
    private javax.swing.JComboBox<String> cmbRendszam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnuLekerdezes;
    private javax.swing.JMenuItem mnuLkDohanyzas;
    private javax.swing.JMenuItem mnuLkKikDolgoztak;
    private javax.swing.JMenuItem mnuLkLeghosszF;
    private javax.swing.JMenuItem mnuLkOszz;
    private javax.swing.JMenuItem mnuPrgBetolt;
    private javax.swing.JMenuItem mnuPrgKilep;
    private javax.swing.JMenuItem mnuPrgMentes;
    private javax.swing.JMenu mnuProgram;
    private javax.swing.JTextField txtFizetesiMod;
    // End of variables declaration//GEN-END:variables
}
